Neo4j Graph Application
==========================

How to use Spring Boot, Spring Data, and Neo4j together.

Spring Data Neo4j enables convenient integration of Neo4j in your Spring-based application.
It provides object-graph mapping (OGM) functionality and other features common to the Spring Data projects.

[NOTE]
This project uses Spring Data Neo4j 6. 

The project uses Java 15.

== Quickstart

First, you need to have a local Neo4j running.
For that use Neo4j desktop, which can be downloaded from here: http://neo4j.com/download.
If you chose that way, install and start as instructed by the desktop application. You need to start a new
database inside desktop.

. After you have Neo4j up and running, open up a browser and goto http://localhost:7474.
Enter the credentials (`neo4j:secret` if you chose the Docker approach above or the credentials you supplied in Neo4j Desktop).

== Code Walkthrough

To use Neo4j with Spring Data Neo4j, you just add the dependency for https://projects.spring.io/spring-boot/[Spring-Boot] and https://projects.spring.io/spring-data-neo4j/[Spring-Data-Neo4j] to your build setup.

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-neo4j</artifactId>
</dependency>
----
include::pom.xml[tags=dependencies]


== The Stack

These are the components of our Web Application:

* Application Type:         Spring-Boot Java Web Application
* Web framework:            Spring-Boot enabled Spring-WebMVC, Spring-Data-Rest
* Persistence Access:       Spring-Data-Neo4j 6.x
* Database:                 Neo4j-Server 4.x
